[package]
name = "wechat-pay-rust-sdk"
version = "0.1.0"
edition = "2021"
authors = ["lake"]
repository = "https://github.com/dounine/wechat-pay-rust-sdk"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
